[package]
name = "torn"
version = "0.1.0"
authors = ["Simon Dickson <simonhdickson@users.noreply.github.com>"]
edition = "2018"
description = """
A minimalist DVD/Bru-ray ripper.
"""
documentation = "https://github.com/simonhdickson/torn"
homepage = "https://github.com/simonhdickson/torn"
repository = "https://github.com/simonhdickson/torn"
readme = "readme.MD"
license = "MIT"

[dependencies]
argh = "0.1"
crossbeam-channel = "0.4"
config = { version = "0.10", default-features = false, features = ["toml"] }
log = "0.4"
heck = "0.3"
humantime-serde = "1.0"
serde = "1.0"
serde_derive = "1.0"
udev = "0.4"
