[options]
sleep_time = "60s"
devices = ["/dev/sr0"]

[directory]
logs = "./logs"
raw = "./raw"
output = "./media"

[makemkv]
args = []

[handbrake.dvd]
extension = "mp4"
preset = "Very Fast 576p25"
args = ["--subtitle", "scan", "-F"]

[handbrake.bluray]
extension = "mp4"
preset = "Very Fast 1080p30"
args = ["--subtitle", "scan", "-F", "--subtitle-burned", "--audio-lang-list", "eng", "--all-audio"]
