[directory]
raw = "./raw"
output = "./media"

[makemkv]
args = []

[handbrake.dvd]
extension = "mkv"
preset = "Fast 576p25"
args = ["--subtitle", "scan", "-F"]

[handbrake.bluray]
extension = "mkv"
preset = "Fast 1080p30"
args = ["--subtitle", "scan", "-F", "--subtitle-burned", "--audio-lang-list", "eng", "--all-audio"]

[omdb]
key = ""
